### ISSUE TITLE
Adding NextPVR Recordings as a Plex Library Not Working Correctly V2

### ISSUE THREAD

**Issue by purevertigo** [psyciknz/NextPVR.bundle#12]
Logs attached.

Foldername 
Whos The Boss

Filename 
Whos The Boss_20170323_15471622.ts
Whos The Boss_20170323_15471622.xml

[Test.zip](https://github.com/psyciknz/NextPVR-Plex/files/864264/Test.zip)

**Comment by psyciknz** [comment]
Hi.  Thanks.   I do see an error In the npvrxml -  looking on my phone so hard to tell.

Can you post the who's the boss episode xml?  I don't need the video just the xml.  And I'll try and load it on mine.

What did standout when quickly looking at the log I saw the keyword opensubtitles - but unsure if this is related or not.

**Comment by psyciknz** [comment]
Sorry, thought the "close and comment" button closed the window...not the issue.  Sorry I'm a moron.

**Comment by purevertigo** [comment]
Attached.

[Whos2.zip](https://github.com/psyciknz/NextPVR-Plex/files/866972/Whos2.zip)

**Comment by purevertigo** [comment]
Is there an ETA for this?

**Comment by psyciknz** [comment]
I just added a .ts file and your XML to a new library and a scan found it.

It's missing the description, but what exactly is the problem....that it's not adding or that the details aren't being added?

**Comment by psyciknz** [comment]
Then I had to do a refresh all metadata, and it appeared.  Do you also have the Scanner installed?  Not just the agent.  The scanner finds the .ts files with the nextpvr name (as it's quite distinctive).  The Agent reads the XML and gets the data.  

I may have a slighter newer version on my system, so I'll upload that to github and you can try again.

**Comment by purevertigo** [comment]
No metadata was the original issue.

**Comment by psyciknz** [comment]
Can you try the latest version in GitHub. I updated it today.

**Comment by purevertigo** [comment]
Tried it already. A refresh Metadata does nothing to import XML.

**Comment by purevertigo** [comment]
Has the fix been located?

**Comment by psyciknz** [comment]
How is the library section configured?  You are using the scanner and agent that I provide? And the library section is set to use both?

Does the show get added to the library with no metadata?  Or is it not added at all.  There's two different problems there.

**Comment by purevertigo** [comment]
The library is configured as per your instructions on the page you made. I am using both agent and scanner and library uses both.

The problem is the show DOES gets added with NO metadata.

**Comment by psyciknz** [comment]
So I just looked at something I recorded last night, and there's no description there either.  Seems it's a bit hit and miss.  As I think you have, refreshing the metadata didn't work either. 

I'll see about having a play around.

**Comment by psyciknz** [comment]
So between my dev system and my main plex system there are differences, probably in some of the add ins I have.  I saw an error when I finally got it going with open subtitles.  And no Im seeing an error where the agent isn't allowed to talk to the plex server to get the media details.  This might be the issue, maybe.  No idea why my other one was able to do it, which made me think it was working (though the other one is not plex pass enabled)

**Comment by purevertigo** [comment]
Hopefully you can find the issue and get the agent working properly.

**Comment by purevertigo** [comment]
Tried latest version. No change.

**Comment by psyciknz** [comment]
You're not giving me much to work with here.   Does anything show up in the npvrxml log?  Ir any thing, errors, or is the log untouched. 

The system log shows the attributes of the agent?

How are you testing it?  I tend to remove a video (and the xml) rescan.  Then put it back in and rescan and I see it fire then.

**Comment by psyciknz** [comment]
So on here, someone had a similar problem and it worked for them: https://forums.plex.tv/discussion/comment/1475769#Comment_1475769

Did you add a token into the config?  That's a new thing where I saw 401 errors in the npvrxml log.

**Comment by psyciknz** [comment]
Also a further question.   Do you record directly to the directory that Plex then accesses?  If so I wonder if Plex is trying to read the files/xml while still being recorded.  And so doesn't attempt again at the end.

I've been playing with a script to copy from an nextpvr directory to a different location that Plex then reads.

**Comment by purevertigo** [comment]
Alright. After taking another look closely. It now works (sort of) thanks to the link you sent me.

The metadata from the XML gets imported properly now but nothing is added from thetvdb at all. No images or descriptions of the show. Another bug?

**Comment by psyciknz** [comment]
Yeah it maybe a case of one or the other.   What may have been happening before is that thetvdb was doing all the work. And the xml reader not firing at all. 

I've set (it's done in code) that thetvdb can contribute to this agent.  I think though, that you have to turn that on in the agent settings.  I'll keep toodling,  but I'm happy that you're at least getting data now.

**Comment by purevertigo** [comment]
You're definitely right, it will have to be 'turned on' somehow.  I've tried checkin it in settings and re-ordering so that it is first but nothing works.

**Comment by psyciknz** [comment]
No I just found the same thing.  I'll see what I actually do for thumbnails.  I know sice doing this initiallity, thumbnail support in nextpvr has increased, as I use it on my channel....so I may be able to piggy back off that, failing that I need to figure out how to defer to another metadata agent somehow.  

Wish the plex community was a little more responsive in help.....

**Comment by psyciknz** [comment]
Should be closed now.  Also the agent has moved to https://github.com/psyciknz/NPVRXML-Plex
