### ISSUE TITLE
CRITICAL (core:561) - Exception (most recent call last):

### ISSUE THREAD

**Issue by snead199** [psyciknz/NextPVR.bundle#3]
I have a PC Quad core/16gb Ram, Plex Media Server, NextPvr are both installed on it. I have always used Plex to push to my Roku devices.

I have intermittent issues with the Live TV menu populating. System, Framework, NextPVR.bundle files are brand new for the logs I am showing. 

The com.dcSoftware.plexapp.nextpvr.log below is an example at 14:55 I press the Roku button to display the Live Menu, It errors out, then press it again(changing nothing) the Menu then displays, files play just fine
![converted 3](https://cloud.githubusercontent.com/assets/7085125/2542907/d2e31106-b5ec-11e3-804c-78c6cc3efaf5.png)

.

**Comment by psyciknz** [comment]
Should be closed.
